version: '3.2'
services:
  text-analysis-all:
    image: maven-taln.upf.edu/beaware/text-analysis-all:20191029
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 10GB
    volumes:
      - type: bind
        source: $RESOURCES
        target: "/resources/"
        read_only: true
    environment:
      - BABELNET_CONFIG=/app/babelnet_config
      - CONCEPT_EN_URL=http://concepts-en.v.taln.ml
      - CONCEPT_ES_URL=http://concepts-es.v.taln.ml
      - GEOLOCATION_URL=http://geolocation.v.taln.ml
      - DISAMBIGUATION_PROPS_EN=/app/disambiguation_en.properties
      - DISAMBIGUATION_PROPS_ES=/app/disambiguation_es.properties
      - COMPACT_DICTIONARY_EN=/resources/BabelNet-4.0.1_en.cache
      - COMPACT_DICTIONARY_ES=/resources/BabelNet-4.0.1_es.cache
      - NER_EN_URL=http://ner_spacy_en.v.taln.ml
      - NER_ES_URL=http://ner_spacy_es.v.taln.ml
      - SYNSETS_FILE=/resources/synsets_3rd_pilot.bin
      - SECRET_MH_API_KEY=xxx
      - SECRET_MH_BROKERS=xxx
      - KAFKA_GROUPID=text-analysis-all-debug-docker