apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: text-analysis-all
  name: text-analysis-all
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: text-analysis-all
    spec:
      containers:
      - env:
        - name: BABELNET_CONFIG
          value: /app/babelnet_config
        - name: CONCEPT_EN_URL
          value: http://concept-candidates:8000
        - name: CONCEPT_ES_URL
          value: http://concept-candidates-es:8000
        - name: GEOLOCATION_URL
          value: http://geolocation:8000
        - name: NER_EN_URL
          value: http://ner-spacy-en:8000
        - name: NER_ES_URL
          value: http://ner-spacy-es:8000
        - name: DISAMBIGUATION_PROPS_EN
          value: /app/disambiguation_en.properties
        - name: DISAMBIGUATION_PROPS_ES
          value: /app/disambiguation_es.properties
        - name: COMPACT_DICTIONARY_EN
          value: /resources/BabelNet-4.0.1_en.cache
        - name: COMPACT_DICTIONARY_ES
          value: /resources/BabelNet-4.0.1_es.cache
        - name: SYNSETS_FILE
          value: /resources/synsets_3rd_pilot.bin
        - name: SECRET_MH_API_KEY
          valueFrom:
           secretKeyRef:
            name: mh-secret2
            key: api_key
        - name: SECRET_MH_BROKERS
          valueFrom:
           secretKeyRef:
            name: mh-secret2
            key: kafka_brokers_sasl
        - name: SECRET_MONGO_URI
          valueFrom:
           secretKeyRef:
            name: mongo-secret
            key: uri
        image: maven-taln.upf.edu/beaware/text-analysis-all:20191031.en-es
        name: text-analysis-all
        resources:
          limits:
            cpu: "1"
            memory: "15Gi"
          requests:
            cpu: "200m"
            memory: "12Gi"
        volumeMounts:
        - mountPath: /resources/
          name: text-analysis-all-claim
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: text-analysis-all-claim
        persistentVolumeClaim:
          claimName: text-analysis-all-claim
          readOnly: true
status: {}
