apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: text-analysis-all
  name: text-analysis-all
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: text-analysis-all
    spec:
      containers:
      - env:
        - name: CONCEPT_URL
          value: http://concept_candidates:8000
        - name: GEOLOCATION_URL
          value: http://geolocation:8000
        image: maven-taln.upf.edu/text-analysis-all:20190218
        name: text-analysis-all
        resources:
          limits:
            cpu: "1"
            memory: "10Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - mountPath: /resources/BabelNet-3.7
          name: text-analysis-all-claim
          readOnly: true
        - mountPath: /resources/sensembed-vectors-merged_bin
          name: text-analysis-all-claim
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: text-analysis-all-claim
        persistentVolumeClaim:
          claimName: text-analysis-all-claim
          readOnly: true
status: {}
